# Generated by Django 5.2.14 on 2026-06-16 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0014_add_batch_forks_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=128, unique=True, verbose_name='实例名称')),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mssql', 'SQL Server')], max_length=16, verbose_name='数据库类型')),
                ('topology', models.CharField(choices=[('standalone', '单实例'), ('ha_cluster', '高可用集群'), ('replication', '复制集成员')], default='standalone', max_length=16, verbose_name='部署拓扑')),
                ('cluster_style', models.CharField(blank=True, choices=[('rac', 'Oracle RAC'), ('galera', 'Galera Cluster'), ('mysql_vip', 'MySQL VIP/代理'), ('proxysql', 'ProxySQL'), ('innodb_cluster', 'MySQL InnoDB Cluster'), ('mgr', 'MySQL Group Replication'), ('patroni', 'PostgreSQL Patroni'), ('pg_vip', 'PostgreSQL VIP/代理'), ('repmgr', 'PostgreSQL repmgr'), ('alwayson', 'SQL Server AlwaysOn'), ('fci', 'SQL Server FCI')], default='', help_text='仅 topology=ha_cluster 时填写', max_length=32, verbose_name='集群类型')),
                ('role', models.CharField(choices=[('master', '主库'), ('slave', '从库')], default='master', max_length=16, verbose_name='实例角色')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('maintenance', '维护中')], default='online', max_length=16, verbose_name='运行状态')),
                ('version', models.CharField(blank=True, default='', max_length=32, verbose_name='版本号')),
                ('connect_host', models.CharField(help_text='本机IP / VIP / SCAN / Listener / 代理地址', max_length=128, verbose_name='连接地址')),
                ('port', models.PositiveIntegerField(verbose_name='连接端口')),
                ('read_connect_host', models.CharField(blank=True, default='', help_text='MySQL Router/ProxySQL 只读入口，可选', max_length=128, verbose_name='只读连接地址')),
                ('read_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='只读连接端口')),
                ('db_name', models.CharField(blank=True, default='', max_length=128, verbose_name='默认库名')),
                ('charset', models.CharField(blank=True, default='', max_length=32, verbose_name='字符集')),
                ('sid', models.CharField(blank=True, default='', max_length=64, verbose_name='Oracle SID')),
                ('service_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Oracle Service Name')),
                ('is_ssl', models.BooleanField(default=False, verbose_name='启用SSL')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.business', verbose_name='所属业务')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.environment', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': '数据库实例',
                'verbose_name_plural': '数据库实例',
                'db_table': 'dbmgr_database_instance',
            },
        ),
        migrations.CreateModel(
            name='DatabaseReplicationCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='复制集名称')),
                ('engine', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('mssql', 'SQL Server')], max_length=16, verbose_name='数据库类型')),
                ('replication_type', models.CharField(choices=[('mysql_replication', 'MySQL主从复制'), ('pg_streaming', 'PostgreSQL流复制'), ('oracle_adg', 'Oracle ADG'), ('mssql_mirror', 'SQL Server镜像/日志传送')], max_length=32, verbose_name='复制类型')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('primary_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_primary_of_replication_clusters', to='dbmgr.databaseinstance', verbose_name='当前主实例')),
            ],
            options={
                'verbose_name': '数据库复制集',
                'verbose_name_plural': '数据库复制集',
                'db_table': 'dbmgr_database_replication_cluster',
            },
        ),
        migrations.AddField(
            model_name='databaseinstance',
            name='replication_cluster',
            field=models.ForeignKey(blank=True, help_text='仅 topology=replication 时使用', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='dbmgr.databasereplicationcluster', verbose_name='所属复制集'),
        ),
        migrations.CreateModel(
            name='DatabaseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('admin', '管理员'), ('readonly', '只读'), ('app', '应用账号'), ('backup', '备份账号')], default='admin', max_length=16, verbose_name='账号类型')),
                ('account_name', models.CharField(max_length=128, verbose_name='账号名称')),
                ('account_pswd', models.CharField(max_length=256, verbose_name='账号密码')),
                ('default_schema', models.CharField(blank=True, default='', max_length=128, verbose_name='默认Schema')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认运维账号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='dbmgr.databaseinstance', verbose_name='关联实例')),
            ],
            options={
                'verbose_name': '数据库账号',
                'verbose_name_plural': '数据库账号',
                'db_table': 'dbmgr_database_account',
                'indexes': [models.Index(fields=['instance', 'is_default'], name='dbmgr_datab_instanc_ec32ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('instance', 'account_name'), name='uniq_dbmgr_instance_account_name')],
            },
        ),
        migrations.CreateModel(
            name='DatabaseInstanceHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(blank=True, default='', max_length=64, verbose_name='节点名称')),
                ('node_sid', models.CharField(blank=True, default='', help_text='Oracle RAC 节点实例 SID，如 ORCL1', max_length=64, verbose_name='节点SID')),
                ('node_service_name', models.CharField(blank=True, default='', max_length=128, verbose_name='节点Service Name')),
                ('listener_host', models.CharField(blank=True, default='', help_text='留空则使用关联主机的业务IP', max_length=128, verbose_name='节点连接地址')),
                ('listener_port', models.PositiveIntegerField(blank=True, help_text='Oracle RAC 节点监听端口，如 11521；MySQL 默认 3306', null=True, verbose_name='节点监听端口')),
                ('is_primary', models.BooleanField(default=False, verbose_name='首选运维节点')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='database_instances', to='common.host', verbose_name='部署主机')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_hosts', to='dbmgr.databaseinstance', verbose_name='关联实例')),
            ],
            options={
                'verbose_name': '实例部署节点',
                'verbose_name_plural': '实例部署节点',
                'db_table': 'dbmgr_database_instance_host',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['instance', 'is_primary'], name='dbmgr_datab_instanc_075eb8_idx')],
                'constraints': [models.UniqueConstraint(fields=('instance', 'host'), name='uniq_dbmgr_instance_host')],
            },
        ),
        migrations.AddIndex(
            model_name='databaseinstance',
            index=models.Index(fields=['engine', 'topology', 'status'], name='dbmgr_datab_engine_7bbec0_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseinstance',
            index=models.Index(fields=['environment', 'business'], name='dbmgr_datab_environ_ad61b0_idx'),
        ),
        migrations.AddIndex(
            model_name='databaseinstance',
            index=models.Index(fields=['replication_cluster'], name='dbmgr_datab_replica_40914a_idx'),
        ),
        migrations.AddConstraint(
            model_name='databaseinstance',
            constraint=models.UniqueConstraint(fields=('engine', 'connect_host', 'port', 'db_name'), name='uniq_dbmgr_instance_endpoint'),
        ),
    ]
