# Generated by Django 5.2.14 on 2026-05-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
            options={
                'verbose_name': '所属业务',
                'verbose_name_plural': '所属业务',
                'db_table': 'common_business',
            },
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
            options={
                'verbose_name': '所属机房',
                'verbose_name_plural': '所属机房',
                'db_table': 'common_data_center',
            },
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
            options={
                'verbose_name': '主机状态',
                'verbose_name_plural': '主机状态',
                'db_table': 'common_host_status',
            },
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
            ],
            options={
                'verbose_name': '主机类型',
                'verbose_name_plural': '主机类型',
                'db_table': 'common_host_type',
            },
        ),
    ]
