# Generated by Django 5.2.14 on 2026-05-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_ostype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, verbose_name='环境编码')),
                ('name', models.CharField(max_length=64, verbose_name='环境名称')),
            ],
            options={
                'verbose_name': '所属环境',
                'verbose_name_plural': '所属环境',
                'db_table': 'common_environment',
            },
        ),
    ]
