# Generated by Django 5.2.14 on 2026-05-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name='环境编码'),
        ),
    ]
