# Generated by Django 5.2.14 on 2026-05-14 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_environment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=128, verbose_name='显示名')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='SSH开放端口')),
                ('admin_user', models.CharField(max_length=64, verbose_name='管理员账号')),
                ('admin_pswd', models.CharField(max_length=256, verbose_name='管理员密码')),
                ('os_version', models.CharField(max_length=64, verbose_name='OS版本')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.business', verbose_name='所属业务')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.datacenter', verbose_name='所属机房')),
                ('host_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.hoststatus', verbose_name='主机状态')),
                ('host_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.hosttype', verbose_name='主机类型')),
                ('os_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.ostype', verbose_name='OS类型')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'db_table': 'common_host',
            },
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=128, verbose_name='容器名称')),
                ('container_id', models.CharField(blank=True, default='', max_length=128, verbose_name='容器ID')),
                ('docker_image', models.CharField(blank=True, default='', max_length=255, verbose_name='镜像名称')),
                ('port_mapping', models.TextField(blank=True, default='', verbose_name='端口映射')),
                ('volume_mount', models.TextField(blank=True, default='', verbose_name='目录挂载')),
                ('cpu_limit', models.CharField(blank=True, default='', max_length=32, verbose_name='CPU限制')),
                ('mem_limit', models.CharField(blank=True, default='', max_length=32, verbose_name='内存限制')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('exited', '已退出')], default='running', max_length=16, verbose_name='容器状态')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='common.host', verbose_name='归属宿主机')),
            ],
            options={
                'verbose_name': 'Docker容器',
                'verbose_name_plural': 'Docker容器',
                'db_table': 'common_docker_container',
            },
        ),
        migrations.CreateModel(
            name='HostAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('adm', '管理'), ('std', '普通')], default='std', max_length=16, verbose_name='账号类型')),
                ('account_name', models.CharField(max_length=64, verbose_name='账号名称')),
                ('account_pswd', models.CharField(max_length=256, verbose_name='账号密码')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='common.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '主机账号',
                'verbose_name_plural': '主机账号',
                'db_table': 'common_host_account',
            },
        ),
        migrations.CreateModel(
            name='HostDomainName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, verbose_name='域名全称')),
                ('domain_type', models.CharField(blank=True, default='', max_length=64, verbose_name='域名类型')),
                ('dns_server', models.CharField(blank=True, default='', max_length=255, verbose_name='域名服务商')),
                ('resolve_ip', models.CharField(blank=True, default='', max_length=255, verbose_name='解析指向')),
                ('status', models.CharField(choices=[('normal', '正常'), ('stop', '已停用'), ('expired', '已过期'), ('pending', '待备案')], default='normal', max_length=16, verbose_name='域名状态')),
                ('is_https', models.BooleanField(default=False, verbose_name='启用HTTPS')),
                ('ssl_expire_time', models.DateTimeField(blank=True, null=True, verbose_name='SSL证书到期时间')),
                ('domain_expire_time', models.DateTimeField(blank=True, null=True, verbose_name='域名到期时间')),
                ('registrant', models.CharField(blank=True, default='', max_length=128, verbose_name='域名负责人')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.business', verbose_name='所属业务')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='common.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '主机域名',
                'verbose_name_plural': '主机域名',
                'db_table': 'common_host_domain',
            },
        ),
        migrations.CreateModel(
            name='HostHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, default='', max_length=128, verbose_name='CPU型号')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU核心数')),
                ('memory', models.CharField(blank=True, default='', max_length=32, verbose_name='内存大小')),
                ('disk', models.CharField(blank=True, default='', max_length=64, verbose_name='磁盘容量')),
                ('disk_detail', models.TextField(blank=True, default='', verbose_name='磁盘明细')),
                ('raid', models.CharField(blank=True, default='', max_length=32, verbose_name='RAID级别')),
                ('vender', models.CharField(blank=True, default='', max_length=128, verbose_name='厂商')),
                ('sn', models.CharField(blank=True, default='', max_length=128, verbose_name='SN序列号')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='维保到期日')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='common.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '硬件信息',
                'verbose_name_plural': '硬件信息',
                'db_table': 'common_host_hardware',
            },
        ),
        migrations.CreateModel(
            name='HostIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64, verbose_name='IP地址')),
                ('ip_type', models.CharField(choices=[('business', '业务IP'), ('inner', '内网IP'), ('outer', '外网IP')], default='business', max_length=16, verbose_name='IP类型')),
                ('nic', models.CharField(max_length=32, verbose_name='使用网卡')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='common.host', verbose_name='关联主机')),
            ],
            options={
                'verbose_name': '主机IP',
                'verbose_name_plural': '主机IP',
                'db_table': 'common_host_ip',
            },
        ),
        migrations.CreateModel(
            name='VmInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virt_platform', models.CharField(choices=[('vmware', 'VMware'), ('kvm', 'KVM'), ('proxmox', 'Proxmox'), ('other', '其他')], default='kvm', max_length=16, verbose_name='虚拟化平台')),
                ('vm_uuid', models.CharField(blank=True, default='', max_length=128, verbose_name='虚拟机UUID')),
                ('resource_pool', models.CharField(blank=True, default='', max_length=128, verbose_name='资源池')),
                ('cluster_name', models.CharField(blank=True, default='', max_length=128, verbose_name='所属集群')),
                ('cpu_quota', models.CharField(blank=True, default='', max_length=32, verbose_name='CPU配额')),
                ('mem_quota', models.CharField(blank=True, default='', max_length=32, verbose_name='内存配额')),
                ('disk_quota', models.CharField(blank=True, default='', max_length=64, verbose_name='磁盘配额')),
                ('snapshot_count', models.IntegerField(default=0, verbose_name='快照数量')),
                ('has_snapshot', models.BooleanField(default=False, verbose_name='是否存在快照')),
                ('auto_start', models.BooleanField(default=False, verbose_name='开机自启')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vm_instance', to='common.host', verbose_name='关联主机')),
                ('parent_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vm_children', to='common.host', verbose_name='归属物理宿主机')),
            ],
            options={
                'verbose_name': '虚拟机实例',
                'verbose_name_plural': '虚拟机实例',
                'db_table': 'common_vm_instance',
            },
        ),
    ]
