# Generated by Django 5.2.14 on 2026-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_host_dockercontainer_hostaccount_hostdomainname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostdomainname',
            name='domain_type',
            field=models.CharField(choices=[('business', '业务域名'), ('admin', '管理后台'), ('test', '测试域名')], default='business', max_length=16, verbose_name='域名类型'),
        ),
    ]
