# Generated by Django 5.2.14 on 2026-05-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_hostdomainname_domain_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='admin_pswd',
        ),
        migrations.RemoveField(
            model_name='host',
            name='admin_user',
        ),
    ]
