# Generated by Django 5.2.14 on 2026-05-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_host_admin_pswd_remove_host_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostaccount',
            name='account_type',
            field=models.CharField(choices=[('adm', '管理员'), ('std', '普通用户')], default='std', max_length=16, verbose_name='账号类型'),
        ),
    ]
