# Generated by Django 5.2.14 on 2026-05-15 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_hostaccount_account_type'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE common_docker_container CHANGE COLUMN docker_image image_name VARCHAR(255) NOT NULL DEFAULT ''",
            reverse_sql="ALTER TABLE common_docker_container CHANGE COLUMN image_name docker_image VARCHAR(255) NOT NULL DEFAULT ''",
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='auto_start',
            field=models.BooleanField(default=False, verbose_name='开机自启'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.business', verbose_name='所属业务'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='command',
            field=models.TextField(blank=True, default='', verbose_name='启动命令'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='container_ip',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='容器IP'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='docker_network',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='所属Docker网络'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='env_list',
            field=models.TextField(blank=True, default='', verbose_name='环境变量'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='image_repository',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='镜像仓库'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='network_mode',
            field=models.CharField(choices=[('bridge', '桥接模式'), ('host', '主机模式'), ('none', '无网络'), ('custom', '自定义网络')], default='bridge', max_length=20, verbose_name='网络模式'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='restart_policy',
            field=models.CharField(choices=[('no', '不重启'), ('always', '总是重启'), ('on-failure', '异常重启')], default='no', max_length=20, verbose_name='重启策略'),
        ),
        migrations.AddField(
            model_name='dockercontainer',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='启动时间'),
        ),
        migrations.AlterField(
            model_name='dockercontainer',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('exited', '已退出'), ('error', '异常')], default='running', max_length=16, verbose_name='容器状态'),
        ),
        migrations.AlterField(
            model_name='dockercontainer',
            name='volume_mount',
            field=models.TextField(blank=True, default='', verbose_name='目录/数据卷挂载'),
        ),
    ]
