# Generated by Django 5.2.14 on 2026-05-16 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_docker_image_dockercontainer_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.scriptcategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '脚本分类',
                'verbose_name_plural': '脚本分类',
                'db_table': 'common_script_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScriptRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='脚本名称')),
                ('script_type', models.CharField(choices=[('shell', 'Shell'), ('python', 'Python'), ('sql', 'SQL'), ('bat', 'Batch'), ('perl', 'Perl'), ('other', '其他')], default='shell', max_length=16, verbose_name='脚本类型')),
                ('content', models.TextField(blank=True, default='', verbose_name='脚本内容')),
                ('description', models.TextField(blank=True, default='', verbose_name='功能描述')),
                ('version', models.CharField(blank=True, default='1.0', max_length=32, verbose_name='版本号')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='common.scriptcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '脚本仓库',
                'verbose_name_plural': '脚本仓库',
                'db_table': 'common_script_repository',
            },
        ),
    ]
