# Generated by Django 5.2.14 on 2026-05-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_add_script_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='pending', max_length=16, verbose_name='任务状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='主机总数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_tasks', to='common.scriptrepository', verbose_name='执行脚本')),
            ],
            options={
                'verbose_name': '批量执行任务',
                'verbose_name_plural': '批量执行任务',
                'db_table': 'common_batch_task',
            },
        ),
        migrations.CreateModel(
            name='BatchTaskHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='执行状态')),
                ('output', models.TextField(blank=True, default='', verbose_name='执行输出')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.host', verbose_name='目标主机')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='common.batchtask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '批量执行-主机结果',
                'verbose_name_plural': '批量执行-主机结果',
                'db_table': 'common_batch_task_host',
            },
        ),
    ]
