# Generated by Django 5.2.14 on 2026-05-31 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_add_batch_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDistTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('source_type', models.CharField(choices=[('local', '本地上传'), ('remote', '远程主机')], default='local', max_length=16, verbose_name='来源类型')),
                ('local_file', models.FileField(blank=True, upload_to='dist_files/%Y%m/', verbose_name='本地上传文件')),
                ('source_path', models.CharField(blank=True, default='', max_length=500, verbose_name='远程源路径')),
                ('dest_path', models.CharField(help_text='目标主机上的落地目录，如 /opt/software/', max_length=500, verbose_name='目标路径')),
                ('dest_owner', models.CharField(blank=True, default='root', max_length=32, verbose_name='文件属主')),
                ('dest_group', models.CharField(blank=True, default='root', max_length=32, verbose_name='文件属组')),
                ('dest_mode', models.CharField(blank=True, default='0644', max_length=8, verbose_name='文件权限')),
                ('backup', models.BooleanField(default=False, verbose_name='备份已有文件')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败')], default='pending', max_length=16, verbose_name='任务状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='主机总数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建人')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_dist_sources', to='common.host', verbose_name='源主机')),
            ],
            options={
                'verbose_name': '文件分发任务',
                'verbose_name_plural': '文件分发任务',
                'db_table': 'common_file_dist_task',
            },
        ),
        migrations.CreateModel(
            name='FileDistTaskHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16, verbose_name='执行状态')),
                ('output', models.TextField(blank=True, default='', verbose_name='执行输出')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.host', verbose_name='目标主机')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='common.filedisttask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '文件分发-主机结果',
                'verbose_name_plural': '文件分发-主机结果',
                'db_table': 'common_file_dist_task_host',
            },
        ),
    ]
