# Generated by Django 5.2.14 on 2026-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_add_file_dist_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='batchtask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
