# Generated by Django 5.2.14 on 2026-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_add_batch_task_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtask',
            name='forks',
            field=models.IntegerField(default=5, verbose_name='并发数'),
        ),
        migrations.AddField(
            model_name='batchtaskhost',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='执行耗时'),
        ),
    ]
